### ISSUE TITLE
why dont use all the data from FaceForensics ?

### ISSUE THREAD

**Issue by zj19921221** [pothabattulasantosh/Detection-of-facial-Manipulated-videos#1]
hi
I have  a question after i download the dataset;
there is thousands of the videos ? why just choose just 100 videos?
why dont use all the data from FaceForensics ?

looking forward your reply

**Comment by pothabattulasantosh** [comment]
Hi,
Definitely we can use all the videos. However, as we can see the results in related paper (FaceForensics++ paper) we can get good enough accuracy with 100  uncompressed videos alone. 

If you are targetting on Low-Quality videos, of-course 100 videos are not sufficient to train the model 

To answer your question, 
using uncompressed videos the model is not learning much after the corpus size=100. Please look at the blow plot (on X-axis it is corpus size, y-axis it is Accuray) 
 
![image](https://user-images.githubusercontent.com/45682222/74527808-a30f0200-4f4c-11ea-838f-142b64345bff.png)

Note: This screenshot is taken from the [original paper](https://arxiv.org/pdf/1901.08971.pdf) 


Thank you

**Comment by zj19921221** [comment]
I am glad to receive your reply. I have another question that how to split the train_set and test_set;
In my opinion it is not proper to split manipulated seq just at  random; It may cause that for example My face in train_set labeled "real"  but in test_set labeled "fake"  
can you help me with it ?

**Comment by pothabattulasantosh** [comment]
Yeah, I got your point, please note that the objective of this project itself is to Detect the manipulated faces. 

Let's stick to your example, as you said if manipulated face video there in test split and authenticated video in train split with the same face, the MODEL should able to RECOGNIZE this.

Even though sometimes both versions of faces look like to be the same for a human eye, but the model should learn to recognize based on low-level artifacts (such as the corrupted nose, eyes, lips, etc).

Hence I believe data split should be random to support our objective.


If you feel I misunderstood your question, please post your query again with little more explanation.

   


Thank you

**Comment by zj19921221** [comment]
hi  can you offer me  the script  of the extracting face of the frame; 
using dlib？

**Comment by zj19921221** [comment]
how do you detect the face on frame； I use a lib from web, found lots of faces cant be detect!
